"""Data and helper function for the "quizzes" test"""

from django.contrib.auth.models import User


def quizzes_data(owner):
    """Generates 4 quizzes with the corresponding questions"""

    from quiz_management_app.models import Quiz, Question

    user2 =User.objects.create(username="testuserTest2", password="123456", email="testuser2@test.de")

    Quiz.objects.create(owner = owner, title = "Lokale KI in VS Code einrichten", description = "Erfahre, wie du lokale KI mit Ollama und VS Code einrichtest, um Code-Assistenten komplett ohne Internetverbindung und Abos zu nutzen.", video_url = "https://www.youtube.com/watch?v=i96JY0zzEZg")
    Quiz.objects.create(owner = owner, title = "Nützliche Webbrowser Tipps und Tricks", description = "Entdecke nützliche und geheime Tipps für deinen Webbrowser, von Design-Modus über Screenshots bis hin zur Tab-Verwaltung und Leistung.", video_url = "https://youtu.be/2ivxA0IhLNY")
    Quiz.objects.create(owner = owner, title = "Der Niedergang von Java und Oracles Lizenzpolitik", description = "Erfahren Sie, warum Java an Marktanteilen verliert, wie Oracle durch Lizenzänderungen Unternehmen abschreckt und ob Java noch zu retten ist.", video_url = "https://youtu.be/pyV20Lhf92U?si=BfYqdAdFdQwKYQ9S")
    Quiz.objects.create(owner = user2, title = "Nützliche Webbrowser Tipps und Tricks", description = "Entdecke spannende und praktische Tipps und Tricks für deinen Webbrowser, von Design-Modus über Screenshots bis hin zur Tab-Verwaltung.", video_url = "https://youtu.be/2ivxA0IhLNY?si=so-tAXdIzdEHMqX4")

    Question.objects.create(question_title = "Welches Tool wird im Video verwendet, um lokale KI auf dem PC zu installieren?", question_options = ["GitHub Copilot", "Ollama", "ChatGPT Desktop", "Claude App"], answer = "Ollama", quiz_id = 1)
    Question.objects.create(question_title = "Wie kann man im Terminal überprüfen, ob Ollama erfolgreich installiert wurde?", question_options = ["ollama --version", "ollama check", "start ollama", "ollama test"], answer = "ollama --version", quiz_id = 1)
    Question.objects.create(question_title = "Welcher Teil von GitHub Copilot funktioniert laut Video nur mit einem Account und einer Internetverbindung?", question_options = ["Der Chat-Agent", "Die Tab-Completions", "Die Dokumentenanalyse", "Die Tool-Nutzung"], answer = "Die Tab-Completions", quiz_id = 1)
    Question.objects.create(question_title = "Wie lädt man ein bestimmtes Modell wie Qwen 3.5 mit 9b Parametern über das Terminal herunter?", question_options = ["ollama get qwen3.5:9b", "ollama download qwen3.5:9b", "ollama pull qwen3.5:9b", "ollama install qwen3.5:9b"], answer = "ollama pull qwen3.5:9b", quiz_id = 1)
    Question.objects.create(question_title = "Welches Hardware-Merkmal ist vor allem entscheidend, um die Größe des lokalen Modells zu bestimmen?", question_options = ["Der Arbeitsspeicher (RAM) der CPU", "Der Festplattenspeicher (SSD/HDD)", "Der Videospeicher (VRAM) der Grafikkarte", "Die Taktfrequenz des Prozessors"], answer = "Der Videospeicher (VRAM) der Grafikkarte", quiz_id = 1)
    Question.objects.create(question_title = "Wie heißt die Extension in VS Code, mit der man die lokalen Ollama-Modelle anbinden kann?", question_options = ["O-Lama", "Local AI", "Code Assistant", "Ollama Copilot"], answer = "O-Lama", quiz_id = 1)
    Question.objects.create(question_title = "Welche Version von Qwen machte laut dem Video Probleme bei der Nutzung von Tools in VS Code?", question_options = ["Qwen 1.5", "Qwen 2.5", "Qwen 3.0", "Qwen 3.5"], answer = "Qwen 2.5", quiz_id = 1)
    Question.objects.create(question_title = "Wie demonstriert der Sprecher im Video, dass die KI wirklich komplett lokal läuft?", question_options = ["Er schaltet den PC aus", "Er trennt die Internetverbindung (Netzwerkkabel)", "Er deinstalliert den Browser", "Er schlie\u00dft alle anderen Programme"], answer = "Er trennt die Internetverbindung (Netzwerkkabel)", quiz_id = 1)
    Question.objects.create(question_title = "Welche konkrete Aufgabe lässt der Sprecher die lokale KI in VS Code ausführen?", question_options = ["Einen Webserver starten", "Eine Test.txt mit dem Wort Banana erstellen", "Einen Python-Code debuggen", "Eine HTML-Datei formatieren"], answer = "Eine Test.txt mit dem Wort Banana erstellen", quiz_id = 1)
    Question.objects.create(question_title = "Welche Institution wird im Video als Arbeitgeber bzw. Plattform des Sprechers genannt?", question_options = ["Developer Academy", "Codecademy", "Udemy", "Coursera"], answer = "Developer Academy", quiz_id = 1)

    Question.objects.create(question_title = "Mit welchem Befehl in der Konsole kann man den Design-Modus einer Website aktivieren?", question_options = ["document.edit = true", "document.design-Mode = on", "enable.design = true", "browser.design = active"], answer = "document.design-Mode = on", quiz_id = 2)
    Question.objects.create(question_title = "Wie erstellt man in Google Chrome am schnellsten einen Screenshot einer gesamten Webseite?", question_options = ["Rechtsklick -> Ganze Seite speichern", "Untersuchen \u00f6ffnen, Steuerung/Cmd + Shift + P dr\u00fccken und 'screenshot' suchen", "F12 dr\u00fccken und 'Full Screenshot' w\u00e4hlen", "Strg + Alt + S"], answer = "Untersuchen öffnen, Steuerung/Cmd + Shift + P drücken und 'screenshot' suchen", quiz_id = 2)
    Question.objects.create(question_title = "Wie aktiviert man die Bild-in-Bild-Funktion für YouTube-Videos in Chrome (unter Windows)?", question_options = ["Einen Rechtsklick machen", "Zweimal einen Rechtsklick auf das Video machen", "Dreimal einen Rechtsklick auf das Video machen", "Die Bild-in-Bild Taste auf der Tastatur dr\u00fccken"], answer = "Zweimal einen Rechtsklick auf das Video machen", quiz_id = 2)
    Question.objects.create(question_title = "Wie öffnet man einen versehentlich geschlossenen Tab in den meisten Browsern wieder?", question_options = ["Strg + Z", "Strg + Shift + T", "Strg + Alt + T", "Strg + Shift + N"], answer = "Strg + Shift + T", quiz_id = 2)
    Question.objects.create(question_title = "Welche Tastenkombination öffnet die Tab-Suche in Chrome?", question_options = ["Strg + Shift + A", "Strg + F", "Strg + Shift + F", "Strg + Alt + A"], answer = "Strg + Shift + A", quiz_id = 2)
    Question.objects.create(question_title = "Wie öffnet man den integrierten Taskmanager von Google Chrome unter Windows?", question_options = ["Strg + Alt + Entf", "Shift + Escape", "F10", "Strg + Shift + T"], answer = "Shift + Escape", quiz_id = 2)
    Question.objects.create(question_title = "Wie kann man eine Internetseite in Chrome schnell auf ein anderes eigenes Gerät (z.B. iPhone) senden?", question_options = ["\u00dcber Bluetooth verbinden", "Per E-Mail teilen", "Rechtsklick und 'An meine Ger\u00e4te senden'", "Den QR-Code scannen"], answer = "Rechtsklick und 'An meine Geräte senden'", quiz_id = 2)
    Question.objects.create(question_title = "Wie kann man von jeder beliebigen Internetseite innerhalb von Sekunden einen QR-Code erstellen?", question_options = ["Rechtsklick und 'QR-Code f\u00fcr diese Seite erstellen'", "In der URL-Leiste 'qr:' eingeben", "Die Druck-Taste dr\u00fccken", "In den Einstellungen auf 'Teilen' gehen"], answer = "Rechtsklick und 'QR-Code für diese Seite erstellen'", quiz_id = 2)
    Question.objects.create(question_title = "Wie öffnet man den Lesemodus in Google Chrome?", question_options = ["\u00dcber das Drei-Punkte-Men\u00fc -> Weitere Tools -> Lesemodus", "Mit der Tastenkombination F9", "Durch einen Doppelklick auf die \u00dcberschrift", "\u00dcber die Lesezeichen-Leiste"], answer = "Über das Drei-Punkte-Menü -> Weitere Tools -> Lesemodus", quiz_id = 2)
    Question.objects.create(question_title = "Wie kann man einen bestimmten Textabschnitt beim Aufrufen einer URL automatisch markieren lassen?", question_options = ["Indem man den Text in Anf\u00fchrungszeichen in die Suche eingibt", "Indem man nach der URL '#:~:text=' gefolgt vom Text anh\u00e4ngt", "Durch das Nutzen einer Browser-Erweiterung", "Das ist technisch nicht m\u00f6glich"], answer = "Indem man nach der URL '#:~:text=' gefolgt vom Text anhängt", quiz_id = 2)

    Question.objects.create(question_title = "Welchen Platz belegt Java laut dem TIOBE-Index heute im Vergleich zu vor zwei Jahrzehnten?", question_options = ["Platz 1", "Platz 2", "Platz 3 bis 4", "Platz 10"], answer = "Platz 3 bis 4", quiz_id = 3)
    Question.objects.create(question_title = "Welche JDK-Distribution verzeichnet laut dem Report ein starkes Wachstum als Community-Build von OpenJDK?", question_options = ["Eclipse-Adoptium", "Microsoft JDK", "Google JDK", "Apple Java"], answer = "Eclipse-Adoptium", quiz_id = 3)
    Question.objects.create(question_title = "Wie rechnet Oracle laut dem neuen Lizenzmodell von 2023 die Subscriptions ab?", question_options = ["Nach genutzter Rechenleistung", "Nach tats\u00e4chlicher Java-Nutzung", "Nach Mitarbeiterzahl", "Nach Zeiteinheit pro Zeile Code"], answer = "Nach Mitarbeiterzahl", quiz_id = 3)
    Question.objects.create(question_title = "Welche Version ist die aktuelle Long-Term-Support-Version (LTS) von Java, die im Video hervorgehoben wird?", question_options = ["Java 8", "Java 11", "Java 17", "Java 21"], answer = "Java 21", quiz_id = 3)
    Question.objects.create(question_title = "Was nennen Unternehmen als Hauptgrund für die aktive Überlegung, Oracle Java zu verlassen?", question_options = ["Schlechte Performance", "Die Kosten", "Mangel an Entwicklern", "Veraltete Syntax"], answer = "Die Kosten", quiz_id = 3)
    Question.objects.create(question_title = "Welche Programmiersprache hat sich nach Googles Ankündigung als offizielle Android-Sprache rasant verbreitet und läuft ebenfalls auf der JVM?", question_options = ["Kotlin", "Swift", "Rust", "Ruby"], answer = "Kotlin", quiz_id = 3)
    Question.objects.create(question_title = "Welche Sprache dominiert laut Video aktuell den Bereich Cloud, Docker und Kubernetes vollständig?", question_options = ["Python", "Go", "PHP", "C++"], answer = "Go", quiz_id = 3)
    Question.objects.create(question_title = "Welches Framework wird im Bereich Cloud-Native als Alternative zu Spring Boot genannt, da es schneller im Native Mode startet?", question_options = ["Django", "Laravel", "Quarkus", "Express"], answer = "Quarkus", quiz_id = 3)
    Question.objects.create(question_title = "Welche Java-Frameworks holen im Bereich Künstliche Intelligenz (AI) rasend schnell auf?", question_options = ["Spring AI und LangChain4J", "TensorFlow Java und PyTorch-J", "AI-Spring und Netty", "OpenAI-Java und Keras"], answer = "Spring AI und LangChain4J", quiz_id = 3)
    Question.objects.create(question_title = "Wer wird laut Fazit im Video Java am ehesten retten?", question_options = ["Oracle selbst", "Die Community und das OpenJDK-\u00d6kosystem", "Die Regierung", "K\u00fcnstliche Intelligenz allein"], answer = "Die Community und das OpenJDK-Ökosystem", quiz_id = 3)

    Question.objects.create(question_title = "Welchen Befehl muss man in der Konsole der Entwickler-Tools eingeben, um Elemente auf einer Webseite zu verändern?", question_options = ["document.edit = true", "document.design-mode = on", "enable.design.mode()", "window.change = 'yes'"], answer = "document.design-mode = on", quiz_id = 4)
    Question.objects.create(question_title = "Welche Tastenkombination öffnet in Chrome den Screenshot-Bereich unter Windows?", question_options = ["Strg + Shift + P", "Strg + Alt + S", "Strg + Shift + S", "F12"], answer = "Strg + Shift + P", quiz_id = 4)
    Question.objects.create(question_title = "Wie aktiviert man die Bild-im-Bild-Funktion für YouTube-Videos in Chrome unter Windows?", question_options = ["Einmal Rechtsklick auf das Video", "Zweimal Rechtsklick auf das Video", "Dreimal Rechtsklick auf das Video", "Strg + Rechtsklick"], answer = "Zweimal Rechtsklick auf das Video", quiz_id = 4)
    Question.objects.create(question_title = "Wie kann man einen versehentlich geschlossenen Tab in gängigen Webbrowsern wieder öffnen?", question_options = ["Strg + Alt + T", "Strg + Shift + Z", "Strg + Shift + T", "Strg + T"], answer = "Strg + Shift + T", quiz_id = 4)
    Question.objects.create(question_title = "Welche Tastenkombination nutzt man in Chrome unter Windows, um alle offenen Tabs zu durchsuchen?", question_options = ["Strg + Shift + A", "Strg + F", "Strg + Alt + A", "Strg + Shift + F"], answer = "Strg + Shift + A", quiz_id = 4)
    Question.objects.create(question_title = "Wie öffnet man den eingebauten Taskmanager von Google Chrome unter Windows?", question_options = ["Strg + Alt + Entf", "Shift + Escape", "F4 + Task", "Strg + Shift + M"], answer = "Shift + Escape", quiz_id = 4)
    Question.objects.create(question_title = "Wie kann man eine Internetseite in Chrome schnell auf dem eigenen Smartphone öffnen?", question_options = ["Mit einem QR-Code Scanner", "\u00dcber Bluetooth teilen", "Per Rechtsklick und 'An meine Ger\u00e4te senden'", "Durch das Kopieren des Caches"], answer = "Per Rechtsklick und 'An meine Geräte senden'", quiz_id = 4)
    Question.objects.create(question_title = "Wo findet man den Lesemodus in Google Chrome?", question_options = ["Unter Einstellungen > Darstellung", "Rechts oben auf die drei Punkte > Weitere Tools > Lesemodus", "Durch die Tastenkombination Strg + L", "Im Men\u00fc der Entwickler-Tools"], answer = "Rechts oben auf die drei Punkte > Weitere Tools > Lesemodus", quiz_id = 4)
    Question.objects.create(question_title = "Wie kann man einen QR-Code für eine beliebige Internetseite in Chrome erstellen?", question_options = ["\u00dcber eine externe Webseite", "Durch Eingabe von qr:// in der URL-Leiste", "Per Rechtsklick auf die Seite und 'QR-Code f\u00fcr diese Seite erstellen'", "Das geht in Chrome nicht"], answer = "Per Rechtsklick auf die Seite und 'QR-Code für diese Seite erstellen'", quiz_id = 4)
    Question.objects.create(question_title = "Wie viel Prozent der Stellen in der IT konnten laut Video im Jahr 2023 in Deutschland nicht besetzt werden?", question_options = ["660.000 Stellen", "149.000 Stellen", "50.000 Stellen", "1.000.000 Stellen"], answer = "149.000 Stellen", quiz_id = 4)